name: Sherpa Onnx TTS/STT
version: "0.2.7"
slug: sherpa_onnx_tts_stt
description: >-
  Sherpa-onnx TTS/STT with wyoming support, supports kokoro-TTS/matcha-TTS/paraformer-STT, requires 1.5GB RAM. 
  离线Sherpa-onnx TTS/STT的wyoming集成，支持kokoro-TTS/matcha-TTS/paraformer-STT，需要1.5G内存。
url: https://github.com/ptbsare/home-assistant-addons/tree/main/sherpa-onnx-tts-stt
arch:
  - amd64
  - aarch64
startup: application
discovery:
  - wyoming
backup_exclude: []
boot: auto
init: false
options:
    language: zh-CN
    speed: 1.0
    stt_model: sherpa-onnx-paraformer-zh-2023-03-28
    stt_use_int8_onnx_model: True
    stt_thread_num: 3
    tts_model: matcha-icefall-zh-baker
    tts_thread_num: 3
    tts_speaker_sid: 0
    debug: True
schema:
    language: str
    speed: float
    stt_model: str
    stt_use_int8_onnx_model: bool
    stt_thread_num: int
    tts_model: |
      list(matcha-icefall-zh-baker|kokoro-multi-lang-v1_0)
    tts_thread_num: int
    tts_speaker_sid: int
    debug: bool
    custom_stt_model: str? 
    custom_stt_model_eval: str?
    custom_tts_model: str? 
    custom_tts_model_eval: str?

ports:
  10400/tcp: 10400
homeassistant: 2023.8.0.dev20230728
image: "ghcr.io/ptbsare/home-assistant-addons/{arch}-addon-sherpa-onnx-tts-stt"
